name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: build
        run: |
          sudo apt install -y lua5.1 lua-markdown lua-penlight
          git clone https://github.com/zhaojh329/ldoc.git
          cd ldoc && sudo make install && cd ..
          ldoc .
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
